### ISSUE TITLE
pretrain weight

### ISSUE THREAD

**Issue by ldxbxl** [sbelharbi/feature-vs-text-compound-emotion#1]
Can I ask where I can find the pre-training weights for vggish and resnet used in your FLAN?

**Comment by ldxbxl** [comment]
Can you please provide me with res50_ir_0.887.pth and vggish.pth, I promise to use them for academic research only!

**Comment by sbelharbi** [comment]
hi, they are already public. you can find them here https://drive.google.com/drive/folders/1yh0vVY-AlwVCDxdAUy_c6e9fVbXUSnF5?usp=sharing .

**Comment by ldxbxl** [comment]
> hi, they are already public. you can find them here https://drive.google.com/drive/folders/1yh0vVY-AlwVCDxdAUy_c6e9fVbXUSnF5?usp=sharing .

Thank you very much.
