### ISSUE TITLE
I can't find train.txt, val.txt, test.txt and class_id.yaml of MELD

### ISSUE THREAD

**Issue by muginekoo** [sbelharbi/feature-vs-text-compound-emotion#2]
When I create split file of MELD, I can't find train.txt, val.txt, test.txt and class_id.yaml for MELD. Can I ask where I can find them?

**Comment by sbelharbi** [comment]
hi,
folds are provided in `./folds` in the root of the repo. if you want to create them again, run `abaw5_pre_processing/dlib/meld.py`. first, uncomment `simplify_csv()` in this last file: 
https://github.com/sbelharbi/feature-vs-text-compound-emotion/blob/ee43219e173669599aa6ae898cba9d3a23ad9494/abaw5_pre_processing/dlib/meld.py#L414C7-L414C21

it will create the folds at https://github.com/sbelharbi/feature-vs-text-compound-emotion/blob/ee43219e173669599aa6ae898cba9d3a23ad9494/abaw5_pre_processing/dlib/meld.py#L154

thanks

**Comment by muginekoo** [comment]
@sbelharbi Thank you very much for the explanation!

**Comment by sbelharbi** [comment]
you are welcome!
closing.
